"""Add follows table

Revision ID: fdbd150def98
Revises: 
Create Date: 2024-06-27 23:15:23.701898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdbd150def98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('user_being_followed_id', sa.Integer(), nullable=False),
    sa.Column('user_following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_being_followed_id'], ['users.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_following_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_being_followed_id', 'user_following_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
